[package]
name = "liblogger"
type = "lib"
build = "make"
repository = "https://github.com/briandowns/liblogger"
version = "1.0.0"
description = "A simple JSON structured logger in C."
homepage = ""
authors = ["Brian Downs"]

[dependencies]
