name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests-and-example:
    name: Tests and Example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install -y libjson-c-dev build-essential
    - name: Compile and test
      run: make && \
            make test && \
            make example
