name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  run-tests-and-example:
    name: Tests and Example
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@main
        - name: Install Dependency
          run: sudo apt install -y libjson-c-dev
        - name: Compile and test
          run: make && \
               make test && \
               make example
